# Generated by Django 4.2.4 on 2024-10-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0098_alter_review_customer_name_alter_review_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchase',
            name='videos',
        ),
    ]
