# Generated by Django 4.2.4 on 2024-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagnoliaCakesAndCupcakes', '0099_remove_userpurchase_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavoursandservingsinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flavoursandservingsinfo',
            name='heading',
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='description1',
            field=models.TextField(default='', verbose_name='Section 1 Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='description2',
            field=models.TextField(default='', verbose_name='Section 2 Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='description3',
            field=models.TextField(default='', verbose_name='Section 3 Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='heading1',
            field=models.CharField(default='', max_length=200, verbose_name='Section 1 Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='heading2',
            field=models.CharField(default='', max_length=200, verbose_name='Section 2 Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='heading3',
            field=models.CharField(default='', max_length=200, verbose_name='Section 3 Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='image1',
            field=models.ImageField(default='', upload_to='flavours_and_servings/', verbose_name='Section 1 Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='image2',
            field=models.ImageField(default='', upload_to='flavours_and_servings/', verbose_name='Section 2 Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='image4',
            field=models.ImageField(default='', upload_to='flavours_and_servings/', verbose_name='Section 4 Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='image5',
            field=models.ImageField(default='', upload_to='flavours_and_servings/', verbose_name='Section 5 Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavoursandservingsinfo',
            name='image6',
            field=models.ImageField(default='', upload_to='flavours_and_servings/', verbose_name='Section 6 Image'),
            preserve_default=False,
        ),
    ]
